package main

InstructionType :: enum {
	NONE,
	LD,
	LDH,
	ADC,
	ADD,
	CP,
	DEC,
	INC,
	SBC,
	SUB,
	AND,
	CPL,
	OR,
	XOR,
	BIT,
	RES,
	SET,
	RL,
	RLA,
	RLC,
	RLCA,
	RR,
	RRA,
	RRC,
	RRCA,
	SLA,
	SRA,
	SRL,
	SWAP,
	CALL,
	JP,
	JR,
	RET,
	RETI,
	RST,
	CCF,
	SCF,
	POP,
	PUSH,
	DI,
	EI,
	HALT,
	DAA,
	PREFIX,
	NOP,
	STOP,
}

RegisterType :: enum {
	NONE,
	A,
	F,
	B,
	C,
	D,
	E,
	H,
	L,
	AF,
	BC,
	DE,
	HL,
	SP,
	PC,
}

getRegisterFromType :: proc(register: RegisterType) -> ^u16 {

	#partial switch register {
	case .A:
		return &cpu.register.AF
	case .F:
		return &cpu.register.AF
	case .AF:
		return &cpu.register.AF
	case .B:
		return &cpu.register.BC
	case .C:
		return &cpu.register.BC
	case .BC:
		return &cpu.register.BC
	case .D:
		return &cpu.register.DE
	case .E:
		return &cpu.register.DE
	case .DE:
		return &cpu.register.DE
	case .H:
		return &cpu.register.HL
	case .L:
		return &cpu.register.HL
	case .HL:
		return &cpu.register.HL
	case .SP:
		return &cpu.register.SP
	case .PC:
		return &cpu.register.PC
	}

	return nil
}

InstructionMode :: enum {
	NONE,
	R_N16,
	R_R,
	MR_R,
	M_R,
	R,
	R_N8,
	R_E8,
	R_MR,
	HLI_R,
	HLD_R,
	R_HLI,
	R_HLD,
	R_A8,
	HL_SPR,
	N16,
	N8,
	IMP,
	N16_R,
	MR_N8,
	MR,
	A16_R,
	R_16,
	E8,
	C_E8,
	C_N16,
}

conditionCode :: enum {
	NONE,
	NZ,
	Z,
	NC,
	C,
}

registerHalf :: enum {
	ALL,
	UPPER,
	LOWER,
	NONE,
}

vec := [8]u8{0x00, 0x08, 0x10, 0x18, 0x20, 0x28, 0x30, 0x38}


instruction :: struct {
	type:          InstructionType,
	addrMode:      InstructionMode,
	reg1:          RegisterType,
	reg2:          RegisterType,
	register1Size: registerHalf,
	register2Size: registerHalf,
	cc:            conditionCode,
	lenght:        u16,
	cycles:        u8,
}

instructions := [0x100]instruction {
	0x00 = {.NOP, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x01 = {.LD, .R_N16, .BC, .NONE, .ALL, .NONE, .NONE, 2, 12},
	0x02 = {.LD, .MR_R, .BC, .A, .NONE, .NONE, .NONE, 0, 8},
	0x03 = {.INC, .R, .BC, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x04 = {.INC, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x05 = {.DEC, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x06 = {.LD, .R_N8, .B, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0x07 = {.RLCA, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x08 = {.LD, .M_R, .NONE, .SP, .NONE, .ALL, .NONE, 2, 20},
	0x09 = {.ADD, .R_R, .HL, .BC, .ALL, .ALL, .NONE, 0, 8},
	0x0A = {.LD, .R_MR, .A, .BC, .UPPER, .ALL, .NONE, 0, 8},
	0x0B = {.DEC, .R, .BC, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x0C = {.INC, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 4},
	0x0D = {.DEC, .R, .C, .NONE, .ALL, .NONE, .NONE, 0, 4},
	0x0E = {.LD, .R_N8, .C, .NONE, .LOWER, .NONE, .NONE, 1, 8},
	0x0F = {.RRCA, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x10 = {.STOP, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 1, 4},
	0x11 = {.LD, .R_N16, .DE, .NONE, .ALL, .NONE, .NONE, 2, 12},
	0x12 = {.LD, .MR_R, .DE, .A, .ALL, .UPPER, .NONE, 0, 8},
	0x13 = {.INC, .R, .DE, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x14 = {.INC, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x15 = {.DEC, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x16 = {.LD, .R_N8, .D, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0x17 = {.RLA, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x18 = {.JR, .E8, .PC, .NONE, .ALL, .NONE, .NONE, 1, 12},
	0x19 = {.ADD, .R_R, .HL, .DE, .ALL, .ALL, .NONE, 0, 8},
	0x1A = {.LD, .R_MR, .A, .DE, .UPPER, .LOWER, .NONE, 0, 8},
	0x1B = {.DEC, .R, .DE, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x1C = {.INC, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 4},
	0x1D = {.DEC, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 4},
	0x1E = {.LD, .R_N8, .E, .NONE, .LOWER, .NONE, .NONE, 1, 8},
	0x1F = {.RRA, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x20 = {.JR, .C_E8, .NONE, .NONE, .NONE, .NONE, .NZ, 1, 12},
	0x21 = {.LD, .R_N16, .HL, .NONE, .ALL, .ALL, .NONE, 2, 12},
	0x22 = {.LD, .HLI_R, .HL, .A, .ALL, .UPPER, .NONE, 0, 8},
	0x23 = {.INC, .R, .HL, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x24 = {.INC, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x25 = {.DEC, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x26 = {.LD, .R_N8, .H, .NONE, .UPPER, .ALL, .NONE, 1, 8},
	0x27 = {.DAA, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x28 = {.JR, .C_E8, .NONE, .NONE, .NONE, .NONE, .Z, 1, 12},
	0x29 = {.ADD, .R_R, .HL, .HL, .ALL, .ALL, .NONE, 0, 8},
	0x2A = {.LD, .R_HLI, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x2B = {.DEC, .R, .HL, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x2C = {.INC, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 4},
	0x2D = {.DEC, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 4},
	0x2E = {.LD, .R_N8, .L, .NONE, .LOWER, .NONE, .NONE, 1, 8},
	0x2F = {.CPL, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x30 = {.JR, .C_E8, .NONE, .NONE, .NONE, .NONE, .NC, 1, 12},
	0x31 = {.LD, .R_N16, .SP, .NONE, .ALL, .NONE, .NONE, 2, 12},
	0x32 = {.LD, .HLD_R, .HL, .A, .ALL, .UPPER, .NONE, 0, 8},
	0x33 = {.INC, .R, .SP, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x34 = {.INC, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x35 = {.DEC, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x36 = {.LD, .MR_N8, .HL, .NONE, .ALL, .NONE, .NONE, 1, 12},
	0x37 = {.SCF, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x38 = {.JR, .C_E8, .NONE, .NONE, .NONE, .NONE, .C, 1, 12},
	0x39 = {.ADD, .R_R, .HL, .SP, .ALL, .ALL, .NONE, 0, 8},
	0x3A = {.LD, .R_HLD, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x3B = {.DEC, .R, .SP, .NONE, .ALL, .NONE, .NONE, 0, 8},
	0x3C = {.INC, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x3D = {.DEC, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 4},
	0x3E = {.LD, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0x3F = {.CCF, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x40 = {.LD, .R_R, .B, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x41 = {.LD, .R_R, .B, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x42 = {.LD, .R_R, .B, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x43 = {.LD, .R_R, .B, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x44 = {.LD, .R_R, .B, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x45 = {.LD, .R_R, .B, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x46 = {.LD, .R_MR, .B, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x47 = {.LD, .R_R, .B, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0x48 = {.LD, .R_R, .C, .B, .LOWER, .UPPER, .NONE, 0, 4},
	0x49 = {.LD, .R_R, .C, .C, .LOWER, .LOWER, .NONE, 0, 4},
	0x4A = {.LD, .R_R, .C, .D, .LOWER, .UPPER, .NONE, 0, 4},
	0x4B = {.LD, .R_R, .C, .E, .LOWER, .LOWER, .NONE, 0, 4},
	0x4C = {.LD, .R_R, .C, .H, .LOWER, .UPPER, .NONE, 0, 4},
	0x4D = {.LD, .R_R, .C, .L, .LOWER, .LOWER, .NONE, 0, 4},
	0x4E = {.LD, .R_MR, .C, .HL, .LOWER, .ALL, .NONE, 0, 8},
	0x4F = {.LD, .R_R, .C, .A, .LOWER, .UPPER, .NONE, 0, 4},
	0x50 = {.LD, .R_R, .D, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x51 = {.LD, .R_R, .D, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x52 = {.LD, .R_R, .D, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x53 = {.LD, .R_R, .D, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x54 = {.LD, .R_R, .D, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x55 = {.LD, .R_R, .D, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x56 = {.LD, .R_MR, .D, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x57 = {.LD, .R_R, .D, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0x58 = {.LD, .R_R, .E, .B, .LOWER, .UPPER, .NONE, 0, 4},
	0x59 = {.LD, .R_R, .E, .C, .LOWER, .LOWER, .NONE, 0, 4},
	0x5A = {.LD, .R_R, .E, .D, .LOWER, .UPPER, .NONE, 0, 4},
	0x5B = {.LD, .R_R, .E, .E, .LOWER, .LOWER, .NONE, 0, 4},
	0x5C = {.LD, .R_R, .E, .H, .LOWER, .UPPER, .NONE, 0, 4},
	0x5D = {.LD, .R_R, .E, .L, .LOWER, .LOWER, .NONE, 0, 4},
	0x5E = {.LD, .R_MR, .E, .HL, .LOWER, .ALL, .NONE, 0, 8},
	0x5F = {.LD, .R_R, .E, .A, .LOWER, .UPPER, .NONE, 0, 4},
	0x60 = {.LD, .R_R, .H, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x61 = {.LD, .R_R, .H, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x62 = {.LD, .R_R, .H, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x63 = {.LD, .R_R, .H, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x64 = {.LD, .R_R, .H, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x65 = {.LD, .R_R, .H, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x66 = {.LD, .R_MR, .H, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x67 = {.LD, .R_R, .H, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0x68 = {.LD, .R_R, .L, .B, .LOWER, .UPPER, .NONE, 0, 4},
	0x69 = {.LD, .R_R, .L, .C, .LOWER, .LOWER, .NONE, 0, 4},
	0x6A = {.LD, .R_R, .L, .D, .LOWER, .UPPER, .NONE, 0, 4},
	0x6B = {.LD, .R_R, .L, .E, .LOWER, .LOWER, .NONE, 0, 4},
	0x6C = {.LD, .R_R, .L, .H, .LOWER, .UPPER, .NONE, 0, 4},
	0x6D = {.LD, .R_R, .L, .L, .LOWER, .LOWER, .NONE, 0, 4},
	0x6E = {.LD, .R_MR, .L, .HL, .LOWER, .ALL, .NONE, 0, 8},
	0x6F = {.LD, .R_R, .L, .A, .LOWER, .UPPER, .NONE, 0, 4},
	0x70 = {.LD, .MR_R, .HL, .B, .ALL, .UPPER, .NONE, 0, 8},
	0x71 = {.LD, .MR_R, .HL, .C, .ALL, .LOWER, .NONE, 0, 8},
	0x72 = {.LD, .MR_R, .HL, .D, .ALL, .UPPER, .NONE, 0, 8},
	0x73 = {.LD, .MR_R, .HL, .E, .ALL, .LOWER, .NONE, 0, 8},
	0x74 = {.LD, .MR_R, .HL, .H, .ALL, .UPPER, .NONE, 0, 8},
	0x75 = {.LD, .MR_R, .HL, .L, .ALL, .LOWER, .NONE, 0, 8},
	0x76 = {.HALT, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0x77 = {.LD, .MR_R, .HL, .A, .ALL, .UPPER, .NONE, 0, 8},
	0x78 = {.LD, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x79 = {.LD, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x7A = {.LD, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x7B = {.LD, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x7C = {.LD, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x7D = {.LD, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x7E = {.LD, .R_MR, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x7F = {.LD, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0x80 = {.ADD, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x81 = {.ADD, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x82 = {.ADD, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x83 = {.ADD, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x84 = {.ADD, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x85 = {.ADD, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x86 = {.ADD, .R_MR, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x87 = {.ADD, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0x88 = {.ADC, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x89 = {.ADC, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x8A = {.ADC, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x8B = {.ADC, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x8C = {.ADC, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x8D = {.ADC, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x8E = {.ADC, .R_MR, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x8F = {.ADC, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0x90 = {.SUB, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x91 = {.SUB, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x92 = {.SUB, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x93 = {.SUB, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x94 = {.SUB, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x95 = {.SUB, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x96 = {.SUB, .R_MR, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x97 = {.SUB, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0x98 = {.SBC, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0x99 = {.SBC, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0x9A = {.SBC, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0x9B = {.SBC, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0x9C = {.SBC, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0x9D = {.SBC, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0x9E = {.SBC, .R_MR, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0x9F = {.SBC, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0xA0 = {.AND, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0xA1 = {.AND, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0xA2 = {.AND, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0xA3 = {.AND, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0xA4 = {.AND, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0xA5 = {.AND, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0xA6 = {.AND, .R_MR, .A, .HL, .UPPER, .ALL, .NONE, 0, 8},
	0xA7 = {.AND, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0xA8 = {.XOR, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0xA9 = {.XOR, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0xAA = {.XOR, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0xAB = {.XOR, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0xAC = {.XOR, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0xAD = {.XOR, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0xAE = {.XOR, .R_MR, .A, .HL, .UPPER, .LOWER, .NONE, 0, 8},
	0xAF = {.XOR, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0xB0 = {.OR, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0xB1 = {.OR, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0xB2 = {.OR, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0xB3 = {.OR, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0xB4 = {.OR, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0xB5 = {.OR, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0xB6 = {.OR, .R_MR, .A, .HL, .UPPER, .LOWER, .NONE, 0, 8},
	0xB7 = {.OR, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0xB8 = {.CP, .R_R, .A, .B, .UPPER, .UPPER, .NONE, 0, 4},
	0xB9 = {.CP, .R_R, .A, .C, .UPPER, .LOWER, .NONE, 0, 4},
	0xBA = {.CP, .R_R, .A, .D, .UPPER, .UPPER, .NONE, 0, 4},
	0xBB = {.CP, .R_R, .A, .E, .UPPER, .LOWER, .NONE, 0, 4},
	0xBC = {.CP, .R_R, .A, .H, .UPPER, .UPPER, .NONE, 0, 4},
	0xBD = {.CP, .R_R, .A, .L, .UPPER, .LOWER, .NONE, 0, 4},
	0xBE = {.CP, .R_MR, .A, .HL, .UPPER, .LOWER, .NONE, 0, 8},
	0xBF = {.CP, .R_R, .A, .A, .UPPER, .UPPER, .NONE, 0, 4},
	0xC0 = {.RET, .NONE, .NONE, .NONE, .NONE, .NONE, .NZ, 0, 20},
	0xC1 = {.POP, .R_R, .AF, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0xC2 = {.JP, .C_N16, .NONE, .NONE, .NONE, .NONE, .NZ, 2, 16},
	0xC3 = {.JP, .N16, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
	0xC4 = {.CALL, .C_N16, .NONE, .NONE, .NONE, .NONE, .NZ, 2, 24},
	0xC5 = {.PUSH, .R_R, .AF, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xC6 = {.ADD, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xC7 = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 16},
	0xC8 = {.RET, .NONE, .NONE, .NONE, .NONE, .NONE, .Z, 0, 20},
	0xC9 = {.RET, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 16},
	0xCA = {.JP, .C_N16, .NONE, .NONE, .NONE, .NONE, .Z, 2, 16},
	0xCB = {.PREFIX, .IMP, .NONE, .NONE, .NONE, .NONE, .NONE, 1, 4}, // TODO: cb instructions
	0xCC = {.CALL, .C_N16, .NONE, .NONE, .NONE, .NONE, .Z, 2, 24},
	0xCD = {.CALL, .N16, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 24},
	0xCE = {.ADC, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xCF = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
	0xD0 = {.RET, .NONE, .NONE, .NONE, .NONE, .NONE, .NC, 0, 20},
	0xD1 = {.POP, .R_R, .DE, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0xD2 = {.JP, .C_N16, .NONE, .NONE, .NONE, .NONE, .NC, 2, 16},
	0xD4 = {.CALL, .C_N16, .NONE, .NONE, .NONE, .NONE, .NC, 2, 24},
	0xD5 = {.PUSH, .R_R, .DE, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xD6 = {.SUB, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xD7 = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
	0xD8 = {.RET, .NONE, .NONE, .NONE, .NONE, .NONE, .C, 0, 20},
	0xD9 = {.RETI, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 16},
	0xDA = {.JP, .C_N16, .NONE, .NONE, .NONE, .NONE, .C, 2, 16},
	0xDC = {.CALL, .C_N16, .NONE, .NONE, .NONE, .NONE, .C, 2, 24},
	0xDE = {.SBC, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xDF = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
	0xE0 = {.LDH, .MR_R, .NONE, .A, .NONE, .UPPER, .NONE, 1, 12},
	0xE1 = {.POP, .R, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0xE2 = {.LDH, .MR_R, .NONE, .C, .UPPER, .LOWER, .NONE, 0, 8},
	0xE5 = {.PUSH, .R, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xE6 = {.AND, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xE7 = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
	0xE8 = {.ADD, .R_E8, .SP, .NONE, .ALL, .NONE, .NONE, 1, 16},
	0xE9 = {.JP, .R, .HL, .NONE, .ALL, .NONE, .NONE, 0, 4},
	0xEA = {.LD, .MR_R, .A, .NONE, .UPPER, .NONE, .NONE, 2, 16},
	0xEE = {.XOR, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xEF = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
	0xF0 = {.LDH, .R_MR, .A, .NONE, .UPPER, .NONE, .NONE, 0, 12},
	0xF1 = {.POP, .R, .AF, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0xF2 = {.LDH, .R_MR, .A, .C, .UPPER, .LOWER, .NONE, 0, 8},
	0xF3 = {.DI, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0xF5 = {.PUSH, .R, .AF, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xF6 = {.OR, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xF7 = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
	0xF8 = {.LD, .R_R, .HL, .SP, .ALL, .ALL, .NONE, 1, 12},
	0xF9 = {.LD, .R_R, .SP, .HL, .ALL, .NONE, .NONE, 0, 8},
	0xFA = {.LD, .R_MR, .A, .NONE, .UPPER, .NONE, .NONE, 2, 16},
	0xFB = {.EI, .NONE, .NONE, .NONE, .NONE, .NONE, .NONE, 0, 4},
	0xFE = {.CP, .R_N8, .A, .NONE, .UPPER, .NONE, .NONE, 1, 8},
	0xFF = {.RST, .N8, .NONE, .NONE, .NONE, .NONE, .NONE, 2, 16},
}

cb_instructions := [0x100]instruction {
	// RLC n (Rotate Left Circular)
	0x00 = {.RLC, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x01 = {.RLC, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x02 = {.RLC, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x03 = {.RLC, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x04 = {.RLC, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x05 = {.RLC, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x06 = {.RLC, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x07 = {.RLC, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// RRC n (Rotate Right Circular)
	0x08 = {.RRC, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x09 = {.RRC, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x0A = {.RRC, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x0B = {.RRC, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x0C = {.RRC, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x0D = {.RRC, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x0E = {.RRC, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x0F = {.RRC, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// RL n (Rotate Left)
	0x10 = {.RL, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x11 = {.RL, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x12 = {.RL, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x13 = {.RL, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x14 = {.RL, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x15 = {.RL, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x16 = {.RL, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x17 = {.RL, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// RR n (Rotate Right)
	0x18 = {.RR, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x19 = {.RR, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x1A = {.RR, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x1B = {.RR, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x1C = {.RR, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x1D = {.RR, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x1E = {.RR, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x1F = {.RR, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// SLA n (Shift Left Arithmetic)
	0x20 = {.SLA, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x21 = {.SLA, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x22 = {.SLA, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x23 = {.SLA, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x24 = {.SLA, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x25 = {.SLA, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x26 = {.SLA, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x27 = {.SLA, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// SRA n (Shift Right Arithmetic)
	0x28 = {.SRA, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x29 = {.SRA, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x2A = {.SRA, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x2B = {.SRA, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x2C = {.SRA, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x2D = {.SRA, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x2E = {.SRA, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x2F = {.SRA, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// SWAP n (Swap upper and lower nibbles)
	0x30 = {.SWAP, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x31 = {.SWAP, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x32 = {.SWAP, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x33 = {.SWAP, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x34 = {.SWAP, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x35 = {.SWAP, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x36 = {.SWAP, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x37 = {.SWAP, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// SRL n (Shift Right Logical)
	0x38 = {.SRL, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x39 = {.SRL, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x3A = {.SRL, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x3B = {.SRL, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x3C = {.SRL, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x3D = {.SRL, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x3E = {.SRL, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x3F = {.SRL, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// BIT 0, n
	0x40 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x41 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x42 = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x43 = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x44 = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x45 = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x46 = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x47 = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// BIT 0, n
	0x48 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x49 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x4A = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x4B = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x4C = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x4D = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x4E = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x4F = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// BIT 2, n
	0x50 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x51 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x52 = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x53 = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x54 = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x55 = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x56 = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x57 = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// BIT 3, n
	0x58 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x59 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x5A = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x5B = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x5C = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x5D = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x5E = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x5F = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// BIT 4, n
	0x60 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x61 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x62 = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x63 = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x64 = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x65 = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x66 = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x67 = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// BIT 5, n
	0x68 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x69 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x6A = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x6B = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x6C = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x6D = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x6E = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x6F = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// BIT 6, n
	0x70 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x71 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x72 = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x73 = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x74 = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x75 = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x76 = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x77 = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// BIT 7, n
	0x78 = {.BIT, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x79 = {.BIT, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x7A = {.BIT, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x7B = {.BIT, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x7C = {.BIT, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x7D = {.BIT, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x7E = {.BIT, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 12},
	0x7F = {.BIT, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// RES 0, n
	0x80 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x81 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x82 = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x83 = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x84 = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x85 = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x86 = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x87 = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// RES 0, n
	0x88 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x89 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x8A = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x8B = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x8C = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x8D = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x8E = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x8F = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// RES 2, n
	0x90 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x91 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x92 = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x93 = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x94 = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x95 = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x96 = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x97 = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// RES 3, n
	0x98 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x99 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x9A = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x9B = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x9C = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0x9D = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0x9E = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0x9F = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// RES 4, n
	0xA0 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xA1 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xA2 = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xA3 = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xA4 = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xA5 = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xA6 = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xA7 = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// RES 5, n
	0xA8 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xA9 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xAA = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xAB = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xAC = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xAD = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xAE = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xAF = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// RES 6, n
	0xB0 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xB1 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xB2 = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xB3 = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xB4 = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xB5 = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xB6 = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xB7 = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// RES 7, n
	0xB8 = {.RES, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xB9 = {.RES, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xBA = {.RES, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xBB = {.RES, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xBC = {.RES, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xBD = {.RES, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xBE = {.RES, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xBF = {.RES, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},

	// SET 0, n
	0xC0 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xC1 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xC2 = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xC3 = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xC4 = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xC5 = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xC6 = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xC7 = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// SET 0, n
	0xC8 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xC9 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xCA = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xCB = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xCC = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xCD = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xCE = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xCF = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// SET 2, n
	0xD0 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xD1 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xD2 = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xD3 = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xD4 = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xD5 = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xD6 = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xD7 = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// SET 3, n
	0xD8 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xD9 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xDA = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xDB = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xDC = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xDD = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xDE = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xDF = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// SET 4, n
	0xE0 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xE1 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xE2 = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xE3 = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xE4 = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xE5 = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xE6 = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xE7 = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// SET 5, n
	0xE8 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xE9 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xEA = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xEB = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xEC = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xED = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xEE = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xEF = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// SET 6, n
	0xF0 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xF1 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xF2 = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xF3 = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xF4 = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xF5 = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xF6 = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xF7 = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	// SET 7, n
	0xF8 = {.SET, .R, .B, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xF9 = {.SET, .R, .C, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xFA = {.SET, .R, .D, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xFB = {.SET, .R, .E, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xFC = {.SET, .R, .H, .NONE, .UPPER, .NONE, .NONE, 0, 8},
	0xFD = {.SET, .R, .L, .NONE, .LOWER, .NONE, .NONE, 0, 8},
	0xFE = {.SET, .MR, .HL, .NONE, .ALL, .NONE, .NONE, 0, 16},
	0xFF = {.SET, .R, .A, .NONE, .UPPER, .NONE, .NONE, 0, 8},
}
